[package]
name = "zero2prod-rust"
description = "Follow along the book zero2prod rust"
version = "0.1.0"
edition = "2021"
authors= ["Abhijeet Vashistha"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
