application:
  host: "127.0.0.1"
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email:
  base_url: "http://localhost/"
  sender: "test@example.com"
  authorization_token: "xxx-xxxx-xxx"
