name: quality

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clippy
        run: cargo clippy

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check
      - name: Run tests
        run: cargo test --verbose
