name: quality

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh
      - name: Clippy
        run: cargo clippy

  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
